name: "Build, test and deploy django_app"
on:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v3
        - name: 'Setup Python'
          uses: actions/setup-python@v3
          with:
            python-version: 3.8

        - name: 'Install requirements and upgrade pip'
          run: |
              python -m pip install --upgrade pip && pip install -r requirements.txt

        - name: 'Django tests'
          run: python manage.py test

  build:
    runs-on: ubuntu-20.04
    needs: tests
    steps:
        - uses: actions/checkout@v3
        - name: 'Build Docker image'
          run: docker build . -t 'django_app:latest'
        

